
    #spring:
    #  datasource:
    #    url: jdbc:h2:mem:default
    #    username: sa
    #    password: 1234
    #    driver-class-name: org.h2.Driver
    #  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    #    hibernate:
    #      generate-ddl: true
    #      ddl-auto: update
    #      show-sql: true
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #      properties:
    #        hibernate:
    #          format_sql: true

    # H2 Settings
#  h2:
#    console:
#      enabled: true
#      path: /h2